# pod2man --section=1 --release="nss-docker" --center=" " --date="20 Oct 2015"
#

=head1 NAME

nss-docker - nss module for finding Docker containers

=head1 SYNOPSIS

libnss_docker.so.2

=head1 DESCRIPTION

This is NSS module for finding Docker containers.

=head1 FILES

=head2 F</etc/nsswitch.conf>

hosts: files docker [NOTFOUND=return] dns

=head1 SEE ALSO

docker(1), nsswitch.conf(5)

=head1 BUGS

If you find the bug or want to implement new features, please report it at
L<https://github.com/dex4er/nss-docker/issues>

=head1 AUTHORS

Copyright (c) 2015 Piotr Roszatycki <dexter@debian.org>

=head1 COPYING

nss-docker is distributed under the GNU Lesser General Public License (LGPL
2.1 or greater).
